services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./volumes/n8n:/home/node/.n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - N8N_HOST=marquetta-shiftable-sacredly.ngrok-free.dev
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://marquetta-shiftable-sacredly.ngrok-free.dev/